backend:
  name: github
  repo: xanderohara1/germ-archives-web
  branch: main  # or the branch you want to use
  use_open_authoring: true
  auth_callback: netlify\make-blog.html
  app_id: 40c4f7199211411ae00c
  base_url: https://api.netlify.com


collections:
  - name: "blogs"
    label: "Blogs"
    folder: "netlify-cms-blogs\blogs"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - { name: "title", label: "Title" }
      - { name: "date", label: "Date", widget: "date" }
      - { name: "featured_image", label: "Featured Image", widget: "image" }
      - { name: "body", label: "Body", widget: "markdown" }
