# netlify.toml

[build]
  command = npm run build  # Replace with your build command
  publish = "dist"           # Replace with your build output directory

[[redirects]]
  from = "netlify\sign-in.html"
  to = "netlify\make-blog.html"
  status = 301
